# Generated by Django 4.2.1 on 2024-04-29 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadigital', '0003_remove_venta_factura_mesa_numero_pedido_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_Hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 20, 57, 30, 284753)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 20, 57, 30, 284753)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 20, 57, 30, 284753)),
        ),
    ]
