# Generated by Django 4.2.1 on 2024-05-14 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartadigital', '0004_alter_pedido_fecha_hora_alter_reserva_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='detalle',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantPersonas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaHora',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_Hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 13, 16, 53, 878698)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 13, 16, 53, 882699)),
        ),
    ]
